### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by tadolphi** [citysciencelab/urban-model-platform#1]
Getting requirements to build wheel: finished with status 'error'
8.272   error: subprocess-exited-with-error
8.272
8.272   × Getting requirements to build wheel did not run successfully.
8.272   │ exit code: 1
8.272   ╰─> [33 lines of output]
8.272       Traceback (most recent call last):
8.272         File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
8.272           main()
8.272         File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
8.272           json_out['return_val'] = hook(**hook_input['kwargs'])
8.272                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
8.272         File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
8.272           backend = _build_backend()
8.272                     ^^^^^^^^^^^^^^^^
8.272         File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
8.272           obj = import_module(mod_path)
8.272                 ^^^^^^^^^^^^^^^^^^^^^^^
8.272         File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
8.272           return _bootstrap._gcd_import(name[level:], package, level)
8.272                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
8.272         File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
8.272         File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
8.272         File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
8.272         File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
8.272         File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
8.272         File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
8.272         File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
8.272         File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
8.272         File "<frozen importlib._bootstrap_external>", line 994, in exec_module
8.272         File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
8.272         File "/tmp/pip-build-env-z_brfnx3/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
8.272           import setuptools.version
8.272         File "/tmp/pip-build-env-z_brfnx3/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
8.272           import pkg_resources
8.272         File "/tmp/pip-build-env-z_brfnx3/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
8.272           register_finder(pkgutil.ImpImporter, find_on_path)
8.272                           ^^^^^^^^^^^^^^^^^^^
8.272       AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
8.272       [end of output]
8.272
8.272   note: This error originates from a subprocess, and is likely not a problem with pip.
8.275 error: subprocess-exited-with-error
8.275
8.275 × Getting requirements to build wheel did not run successfully.
8.275 │ exit code: 1
8.275 ╰─> See above for output.
8.275
8.275 note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by tadolphi** [comment]
SOLUTION:

Change from 
FROM python:3 => FROM python:3.11

in api/Dockerfile

did it.
